version: "3.8"

services:
  roadmap:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 3.0
        LOCATION: target
    image: vcontu/roadmap
    container_name: roadmap
    hostname: roadmap
    ports:
      - "8080:8080"
    environment:
      ROADMAP_CONFIG_PATH: /config
    volumes:
      - '/host_mnt/c/Users/vcontu/practice/roadmap/config/roadmap.properties:/config/roadmap.properties'
    restart: on-failure
    networks:
      - roadnet
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
#  oracle:
#    image: 'oracle/database:12.2.0.1-ee'
#    container_name: oracle-rd
#    hostname: oracle
#    environment:
#      ORACLE_SID: orcl
#      ORACLE_PDB: orclpdb
#      ORACLE_PWD: orclpass
#    ports:
#      - "1521:1521"
#    networks:
#      - roadnet
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "50m"
#        max-file: "1"

networks:
  roadnet:
    external: true
#    driver: bridge
