# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET /users
Host: localhost:8080
Accept: application/json
###

GET /users/lsky
Host: localhost:8080
Accept: application/json
###

POST /users
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
  "username": "wwonka",
  "nickname": "Willie Wonka",
  "email": "w.wonka@gmail.com",
  "role": "CLIENT",
  "credits": 0,
  "active": true
}
###

GET /users/wwonka
Host: localhost:8080
Accept: application/json
###


PUT /users/wwonka
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
  "username": "willie",
  "nickname": "Waka Waka",
  "email": "waa@gmail.com",
  "role": "CLIENT",
  "credits": 0,
  "active": true
}
###

DELETE /users/willie
Host:localhost:8080
Content-Type: application/json
Accept: application/json

###

