spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:db;Mode=Oracle;DB_CLOSE_DELAY=-1'
    username: sa
    password: sa
    data: 'classpath:db/h2/*.sql'
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate.ddl-auto: create
  h2.console:
    enabled: true
    path: /h2-console