spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: '@db.url@'
    username: @db.user@
    password: @db.password@
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate.ddl-auto: validate