ALTER TABLE USERS
ADD BALANCE NUMBER(6) DEFAULT 0;

ALTER TABLE USERS
MODIFY (BALANCE DOUBLE PRECISION );

ALTER TABLE USERS
MODIFY (BALANCE NUMBER(19,2) );

ALTER TABLE CREDIT_HISTORY
MODIFY (AMOUNT NUMBER );